@startuml
class EncodingModule {
+ void encodeWithFiles()
+ void encodeBasedOnNetworkAndDatabase()
}
class EncodingModuleClient {
+ {static} void main(String[])
}
class MyDatabase {
- {static} Map<Integer,String> _data
- {static} int _count
+ int write(String)
}
@enduml