@startuml
class Robot {
+ String work()
+ String eat()
}
class Human {
+ String work()
+ String eat()
}
interface Worker {
~ String work()
~ String eat()
}
class MessHall {
- List<Worker> _workers
+ void manage()
}
class Factory {
- List<Worker> _workers
+ void manage()
}


Worker <|.. Robot
Worker <|.. Human
@enduml