@startuml
class com.directi.training.lsp.example.RectangleTest {
+ void testSetWidth_Rectangle()
+ void testSetWidth_Square()
}
class com.directi.training.lsp.example.Rectangle {
# int _width
# int _height
+ int getWidth()
+ void setWidth(int)
+ int getHeight()
+ void setHeight(int)
+ int getArea()
}
class com.directi.training.lsp.example.Square {
+ void setWidth(int)
+ void setHeight(int)
}


com.directi.training.lsp.example.Rectangle <|-- com.directi.training.lsp.example.Square
@enduml