@startuml
abstract class Shape {
+ {abstract}double getArea()
}
class Circle {
- double _radius
+ double getRadius()
+ double getArea()
}
class Square {
- double _side
+ double getSide()
+ double getArea()
}
class AreaCalculator {
+ void calculateArea(List<Shape>)
}


Shape <|-- Circle
Shape <|-- Square
@enduml