@startuml
class EmployeeFormatter {
- Employee _employee
+ String toHtml()
+ String formatManager(String)
}
class Employee {
- {static} int LEAVES_ALLOWED
- int _empId
- String _name
- double _monthlySalary
- String _manager
- int _leavesTaken
- int _yearsInOrg
- int[] _leavesLeftPreviously
+ int getEmpId()
+ String getName()
+ int getLeavesLeft()
+ long getAnnualSalary()
+ int getTotalLeavesLeftPreviously()
+ String getManager()
}
@enduml