@startuml
class Employee {
- {static} int LEAVES_ALLOWED
- int _empId
- String _name
- double _monthlySalary
- String _manager
- int _leavesTaken
- int _yearsInOrg
- int[] _leavesLeftPreviously
+ String toHtml()
}
@enduml